### ISSUE TITLE
[TKGm on vSphere with vDS] - inconsistent naming of port groups, networks and segments

### ISSUE THREAD

**Issue by BrianRagazzi** [vmware-tanzu-labs/tanzu-validated-solutions#11]
The network diagram Clearly shows the following network names: NSX ALB Management Port Group, TKG Management Port Group, TKG Management VIP Port Group, TKG Cluster VIP Port Group, TKG Workload Data VIP Port Group and TKG Workload Port Group 01.  

Example Network Entries in the install guide matches except uses "Network" instead of Port Group, except "TCG Workload Segment"

The Arcas Wizard mixes the terms DHCP Start/End Range and Cluster VIP Start/End Range in the VMware NSX ALB Section
The Arcas Wizard prompts for a segment name under TKG Management Data Network, but it is unclear whether "TKG Management Data Network" is the "TKG Management Port Group" or the "TKG Management Data VIP Port Group"
The Arcas Wizard under Management Cluster Settings prompts for "Network Segment Name" rather than "TKG Management Port Group"
The Arcas Wizard prompts for a segment name under TKG Workload Data Network, but it is unclear whether "TKG Management Data Network" is the "TKG Workload Port Group" or the "TKG Workload Data VIP Port Group"
The Arcas Wizard prompts for a DHCP Start/End Range under TKG Workload Data Network, but it is unclear whether the is teh EXTERNALLY-CONFIGURED DHCP scope or will be used as the usable range for this network.

**Comment by smuthukumar-vmw** [comment]
[https://docs.vmware.com/en/VMware-Tanzu-for-Kubernetes-Operations/2.1/tko-reference-architecture/GUID-deployment-guides-tko-on-vsphere.html#deploy-mgmg-cluster](url) addresses the query on arcas prompting and usage of portgroups.

SIVT aka ARCAS adheres to the RA network requirement updated here [https://docs.vmware.com/en/VMware-Tanzu-for-Kubernetes-Operations/2.1/tko-reference-architecture/GUID-reference-designs-tko-on-vsphere.html#subnet-and-cidr-examples-14](url)
