### ISSUE TITLE
Change graphics in dark background to light for TKO on vSphere with NSX-ALB (tko-on-vsphere.md)

### ISSUE THREAD

**Issue by msegvich** [vmware-tanzu-labs/tanzu-validated-solutions#114]
Use light background or light theme for any images. Currently there's a mix of light and dark.

**Comment by nithink-vmw** [comment]
Except VMC, all other docs are having lighter team on RA 1.5

**Comment by manishjha86** [comment]
As Nithin mentioned, only VMC doc has now dark theme graphics. We will use lighter theme images when do we RA/DG refresh for TKG 1.6.
