### ISSUE TITLE
Deployment guide for TKG on vSphere updates for least privileged account credentials

### ISSUE THREAD

**Issue by calebwashburn** [vmware-tanzu-labs/tanzu-validated-solutions#117]
**Is your feature request related to a problem? Please describe.**
The current deployment guide (https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/blob/main/src/deployment-guides/tko-on-vsphere.md) recommends using administrator account for both AVI and TKG.

**Describe the solution you'd like**
Update to document least privileged account for both TKG and AVI service accounts.

**Describe alternatives you've considered**

**Additional context**
Desired state is to not use super user/admin accounts for security reasons.

**Comment by calebwashburn** [comment]
For AVI account to vsphere this exists - https://avinetworks.com/docs/latest/vmware-user-role/

**Comment by smuthukumar-vmw** [comment]
From 2.x RA, we have included the required permissions for vSphere account. [https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/2.1/tkg-deploy-mc-21/mgmt-reqs-prep-vsphere.html#required-permissions-for-the-vsphere-account-5](url)

For AVI Integration roles, we are working on [https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/issues/118](url) on which we will include the roles specified from [https://avinetworks.com/docs/latest/vmware-user-role/](url).
