### ISSUE TITLE
[TKGm on vSphere with vDS] - please reconcile AKO configuration params with AKO Tunables

### ISSUE THREAD

**Issue by BrianRagazzi** [vmware-tanzu-labs/tanzu-validated-solutions#12]
The Parameters in the AKODeploymentConfig do not fully mesh with the AKO Tunables found here:  https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/blob/release-1.5.1/docs/values.md#l7settingsservicetype
Specifically interested in configuration of AKO in ClusterIP mode in addition to L7 capabilities vs AKO in NodePort Mode

**Comment by ranjith-bp87** [comment]
@BrianRagazzi  AVI l7 is yet to be included and will be included in an upcoming release

**Comment by smuthukumar-vmw** [comment]
RA [https://docs.vmware.com/en/VMware-Tanzu-for-Kubernetes-Operations/2.1/tko-reference-architecture/GUID-reference-designs-tko-on-vsphere.html](url) address the L7 capabilities on multiple modes [https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/2.1/tkg-deploy-mc-21/mgmt-reqs-network-nsx-alb-ingress.html](url)
