### ISSUE TITLE
fixes to RA landing page

### ISSUE THREAD

**Issue by srivar** [vmware-tanzu-labs/tanzu-validated-solutions#13]
Let's make following changes to the RA landing page https://docs.vmware.com/en/VMware-Tanzu/services/tanzu-reference-architecture/GUID-TKG-reference-architecture-overview.html.

Consult with Simone Morellato on below (Simone leads Tanzu Marketing).

1. First paragraph is referring to TKO-specific value prop - replace with generic Tanzu marketing messaging - let's obtain from Simone

2. Before the second paragraph - insert a new para that informs the reader that the current set of RAs are focused on TKO, more to follow soon on other Tanzu "bundles" (TAP, etc.). Needs to be worded in market-friendly language (again consult with Simone on how/what to say

3. Replace the diagram below second paragraph with whatever Simone recommends. For example - current diagram is missing TSM.

4. Delete the "Networking Overview" section. Its high-level and serves no value existing at this level.

**Comment by srivar** [comment]
https://jira.eng.vmware.com/browse/MAPBUA-423

**Comment by srivar** [comment]
https://jira.eng.vmware.com/browse/TNZDOC-61

**Comment by srinivasme21** [comment]
All items in this issue are fixed and published.
