### ISSUE TITLE
Architecture Diagrams in Reference design on vSphere incorrectly refers to vSphere with Tanzu and VCF

### ISSUE THREAD

**Issue by samikshajuneja** [vmware-tanzu-labs/tanzu-validated-solutions#132]
**Describe the bug**
The architecture diagram in reference design for TKO on vSphere uses the term "vSphere with Tanzu" to describe the underlying infrastructure. Similar is the case with the 'TKO on vSphere with NSX' it has used the term "VCF with Tanzu".

**Screenshots**
![image](https://user-images.githubusercontent.com/38665322/161775919-878a7d81-5f4c-484c-9d00-7b705629b2b1.png)
![image](https://user-images.githubusercontent.com/38665322/161776017-f652f2bf-fdc2-4f4c-b1d7-23dd6865a4dc.png)

**Additional context**
 I am having thoughts about these as they might cause the confusion. It'll be great to understand your perspective for using them.

**Comment by manishjha86** [comment]
This has been already taken care of in RA 2.0
