### ISSUE TITLE
Design recommendation for management and workload clusters can be included in reference design [for TKO on vSphere and vSphere with Tanzu)

### ISSUE THREAD

**Issue by samikshajuneja** [vmware-tanzu-labs/tanzu-validated-solutions#133]
**Describe the bug**
Just like  TKO on vSphere with NSX has "Design recommendation for Management and Workload Clusters" section. It can be copied to reference design documents for "TKO on vSphere " as well. 

**Screenshots**
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/38665322/161777879-b2ff2da7-7e9c-4fc7-9251-dce8a03416de.png">

**Additional context**
Adding up the section in other vSphere documents will help the sellers to design these clusters for customer or even remind them to add them in demonstration to the customer. 

I'll be happy to understand your thought, concerns.

**Comment by manishjha86** [comment]
This has been already taken care of in RA 2.0
