### ISSUE TITLE
Include brief about NSX Advanced Load Balancer in TKO on vSphere 

### ISSUE THREAD

**Issue by samikshajuneja** [vmware-tanzu-labs/tanzu-validated-solutions#134]
**Describe the bug**
We can include brief about the NSX advanced Load Balancer in TKO on vSphere. Content from TKO on vSphere with Tanzu can be restated here. 

**Screenshots**
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/38665322/161779582-b987a032-f1d0-41fd-a1a2-590a076a5e3b.png">

**Additional context**
It can be handy for the seller who is positioning the TKO on vSphere as a solution.

**Comment by manishjha86** [comment]
This has been already taken care of in RA 2.0
