### ISSUE TITLE
Firewall Recommendation under reference design for TKO on vSphere with Tanzu

### ISSUE THREAD

**Issue by samikshajuneja** [vmware-tanzu-labs/tanzu-validated-solutions#135]
**Describe the bug**
Firewall recommendation section under TKO on vSphere with Tanzu contains two additional recommendations as compared to "TKO on vSphere and TKO on Vsphere with NSX" . Is it possible to add them in "TKO on vSphere and TKO on Vsphere with NSX" as well?

Firewall recommendation :
    1. NSX Advanced Load Balancer Controller node IP address. —**(Mgmt CIDR is already mentioned so I guess this one is not needed)**
    2. NSX Advanced Load Balancer Service Engine management & data IP address.

**Comment by manishjha86** [comment]
@samikshajuneja can you please provide a reference to the exact firewall rules that you are referring to.

**Comment by smuthukumar-vmw** [comment]
Firewall requirements have been added for TKO on[ vSphere and TKO on vSphere](https://docs.vmware.com/en/VMware-Tanzu-for-Kubernetes-Operations/2.1/tko-reference-architecture/GUID-reference-designs-tko-on-vsphere.html#firewall-requirements-18) with[ NSX-T ](https://docs.vmware.com/en/VMware-Tanzu-for-Kubernetes-Operations/2.1/tko-reference-architecture/GUID-reference-designs-tko-on-vsphere-nsx.html#firewall-requirements-9)in the RA. Thanks.
