### ISSUE TITLE
Contour Ingress section/option can be included in TKO on vSphere with Tanzu

### ISSUE THREAD

**Issue by samikshajuneja** [vmware-tanzu-labs/tanzu-validated-solutions#136]
**Describe the bug**
We can add or restate (from TKO on vSphere) the Contour Ingress in reference design for " TKO on vSphere with Tanzu".

**Additional context**
It will be great for Solution Engineers who are gonna implement or design with Contour as an Ingress option. I'll be glad to know your perspective.

**Comment by manishjha86** [comment]
We have created a dedicated MD file for installing user-managed packages in workload clusters (both tkgm and tkgs). All deploy guides will cross-reference this MD file for instructions on installing packages. 

Link tp package install doc: https://github.com/manishjha86/tanzu-validated-solutions/blob/tanzu-packages-dg/src/deployment-guides/tkg-package-install.md

Until all docs related to 1.5 is merged in the main branch, we won't be able to see this.
