### ISSUE TITLE
Add vSphere Multi-Cluster design option in reference design for TKO on vSphere with Tanzu

### ISSUE THREAD

**Issue by samikshajuneja** [vmware-tanzu-labs/tanzu-validated-solutions#137]
**Describe the bug**
If it is acceptable to add the vSphere multi-cluster option to "TKO on vSphere with Tanzu" then we should do so as it will give more convenience to design for customers having large and complex workloads.

**Comment by manishjha86** [comment]
This will be addressed in RA 3.0

**Comment by smuthukumar-vmw** [comment]
@samikshajuneja  could you explain briefly on the "vSphere multi-cluster option to "TKO on vSphere with Tanzu" feature. Also, upcoming RA would cover multi-AZ involving multi-cluster for TKO on vSphere with Tanzu.

**Comment by smuthukumar-vmw** [comment]
https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.6/vmware-tanzu-kubernetes-grid-16/GUID-tanzu-k8s-clusters-multi-az-vsphere.html is also covering the same. Upcoming RA 2.3 is also intended to cover multi-AZ and multi-DC scenarios.
