### ISSUE TITLE
TSM section can be restated from 'TKO on vSphere with Tanzu' to "TKO on vSphere and NSX" . 

### ISSUE THREAD

**Issue by samikshajuneja** [vmware-tanzu-labs/tanzu-validated-solutions#138]
**Describe the bug**
In reference design, TSM section can be restated from 'TKO on vSphere with Tanzu' to "TKO on vSphere and NSX" .

**Comment by manishjha86** [comment]
This has been taken care in RA 2.0

All RA/DG now points to a dedicated md file for saas. This md file talks about TKG integration with  SaaS

Sample File: https://github.com/manishjha86/tanzu-validated-solutions/blob/tko-saas-ra/src/reference-designs/tko-saas.md
