### ISSUE TITLE
Present TO as preferred option to Prometheus/Grafana in vSphere RAs

### ISSUE THREAD

**Issue by srivar** [vmware-tanzu-labs/tanzu-validated-solutions#14]
Emulate in vSphere RAs how TO is presented as a preferred option visa-vis P/G in AWS RA - https://docs.vmware.com/en/VMware-Tanzu/services/tanzu-reference-architecture/GUID-TKO-on-aws-ref-design.html.

In vSphere RAs we are mapping TO to Tanzu Advanced and P/G to Standard. While that's technically accurate, we want to re-word as is done in AWS RA (search for TO and P/G to see the difference).

P.S. Minor related bug fix - in vSphere/vDS RA - remove last line in Summary - "Observability is quickly established and easily consumed with Tanzu Observability."

**Comment by srinivasme21** [comment]
Updated in PR #105.
