### ISSUE TITLE
Command to initiate cluster deployment needs to be updated

### ISSUE THREAD

**Issue by shaqster** [vmware-tanzu-labs/tanzu-validated-solutions#140]
**Describe the bug**
In the vSphere [tko-on-vsphere](https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/tree/main/src/deployment-guides/img/tko-on-vsphere) deployment guide, in section Deploy Tanzu Shared Service Cluster,  `tanzu cluster create -f <path-to-config.yaml> -v 6 ` should be updated to `tanzu cluster create CLUSTERNAME -f <path-to-config.yaml> -v 6` when initiating cluster deployment with Tanzu CLI 1.4.x

**Comment by manishjha86** [comment]
Providing cluster name is not mandatory in the command line. if the cluster name is already specified in the cluster deployment file, then the tanzu cluster create command do not error out.
