### ISSUE TITLE
Documentation steps do not include screenshots as the changes are difficult to catchup for users

### ISSUE THREAD

**Issue by arunavasan** [vmware-tanzu-labs/tanzu-validated-solutions#16]
For eg: [this section ](https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/blob/main/refarchitecture/unpublished/vmware-tanzu-deployment-on-vsphere.md#-deploy-nsx-advanced-load-balancer)has 12 steps and its not easy to find where the user has to find this option and which portal he has to be on etc. Through out the documentation there is no screenshots or images for users to follow it easily. 

Verbose steps are overwhelming for users to follow.

**Comment by ranjith-bp87** [comment]
@arunavasan can you please share the section we are talking about? Provided link is not working.

**Comment by srivar** [comment]
@arunavasan - can you point us to the relevant section in latest version of deployment guide?

**Comment by smuthukumar-vmw** [comment]
@arunavasan While the latest DG have included screenshots and explanation of the changes, please do reopen the issue with the right link, if you find otherwise. Thanks.
