### ISSUE TITLE
Cleanup Image within TKO on AWS

### ISSUE THREAD

**Issue by brharr** [vmware-tanzu-labs/tanzu-validated-solutions#169]
**Describe the bug**
Within the Global Cluster Lifecycle Management section of the document, the first image is very badly formatted, layed out and doesn't have the same color background as the rest of the images. Please cleanup and reformat to match the cleanness of the others.

**Comment by sendjainabhi** [comment]
PR #176 will have cleaned images from vmware graphics team.
