### ISSUE TITLE
Add steps for configuring a DNS profile to the AVI section

### ISSUE THREAD

**Issue by itgrl-bex** [vmware-tanzu-labs/tanzu-validated-solutions#170]
While on an engagement we had issues with AVI setup and engaged support.  AVI support stated that a DNS profile is required for AVI. Since AVI support stated this is a requirement, we should add a section to the Reference Architecture near the IPAM profile section.  Link to Vsphere with Tanzu section provided, but this would be required for all AVI deployments.

https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/blob/main/src/deployment-guides/tko-on-vsphere-with-tanzu.md#configure-ipam

**Comment by manishjha86** [comment]
We will fix this in all RA 2.0 docs

**Comment by JefeDavis** [comment]
I've actually done several engagements for vSphere with Tanzu and AVI, I have never needed to create a DNS profile, from my understanding a DNS profile is only needed if AVI is going to be acting as a DNS provisioner, or if not using another solution like externalDNS. Is this a new requirement? If so, I would love to see the reason why it is needed, did support send you any documentation on why they believe this is necessary?

**Comment by itgrl-bex** [comment]
I also have set up TKGs and AVI without a DNS profile and have not been able to find official support documentation stating it is needed.  We may be able to close this issue as this last engagement we stood up TKGs and AVI without a DNS profile and it is working.

**Comment by manishjha86** [comment]
Although adding DNS profile is not a mandatory setting for tkgm/tkgs deployment, I have added it in vmc on was and tko on vwt deploy guides.
