### ISSUE TITLE
Issues installing user managed packages after integrating with SAAS products

### ISSUE THREAD

**Issue by itgrl-bex** [vmware-tanzu-labs/tanzu-validated-solutions#172]
**Describe the bug**
We lost a lot of time due to troubleshooting issues related to compatibility, specifically with User Managed Packages and TSM.

**To Reproduce**
Please provide the steps to reproduce the behavior or a description of the content defect.
1. Go to https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/blob/main/src/deployment-guides/tko-on-vsphere-with-tanzu.md#--deploy-user-managed-packages-on-tanzu-kubernetes-grid-clusters
2. Integrate a workload cluster with SAAS products, especially TSM
3. After integrating SAAS products to your workload cluster to to TMC and attempt to deploy packages. I'm assuming the Tanzu CLI will have the same results.
4. The carvel packages will fail to reconcile.

**Expected behavior**
All packages should reconcile and install without issue.

**Additional context**
What was found is that Tanzu Service Mesh will inject proxy containers if deployed for all namespaces.  This has conflicts with most, if not all, the user packages.  The user packages such as cert-manager, contour, Prometheus, and Grafana should be installed prior to integrating with Tanzu Service Mesh or you will see failures.  After installing the 4 packages mentioned above and then integrating with TSM and excluding the namespaces of cert-manager, tanzu-system-ingress, tanzu-system-monitoring, and tanzu-system-dashboards, we were able to completely deploy TKGs with 2 workload clusters, the 4 carvel packages, TO, TMC, and TSM in less than 3 hours.  This took days prior due to the TSM and carvel package conflicts.

**Comment by nithink-vmw** [comment]
Manish will follow up with TSM team to confirm the work flow and file bug incase required to track as TSM issue.

**Comment by manishjha86** [comment]
Email sent to TSM team with the above query. Documentation will be updated after getting a response from the TSM team.

**Comment by manishjha86** [comment]
I have got the following response from the TSm team.
`Adding Mark & Ganesh.

Manish – you should be able to exclude namespaces when TSM is installed – so I would suggest simply excluding the user packages, the order in which packages are deployed is not critical. 

Ganesh can follow up with you if you have further queries since Mohana is on PTO.

Thx
Deepa
`

As per the above comment, we will add a couple of lines in the TKO 1.5 docs in the TSM installation section about excluding namespaces.

**Comment by itgrl-bex** [comment]
Agreed the order is not critical, but from a delivery standpoint, it is easier to direct the customer to select an existing namespace rather than type it in when installing TSM.  If you install the user-managed packages prior to installing TSM then the required namespaces to exclude are in the dropdown menu.


Becca Robinson
Staff Solution Architect - Tanzu Platform Services


From: Manish Jha ***@***.***>
Date: Tuesday, July 12, 2022 at 12:06 AM
To: vmware-tanzu-labs/tanzu-validated-solutions ***@***.***>
Cc: Becca Robinson ***@***.***>, Assign ***@***.***>
Subject: Re: [vmware-tanzu-labs/tanzu-validated-solutions] Issues installing user managed packages after integrating with SAAS products (Issue #172)

⚠ External Email

I have got the following response from the TSm team.
`Adding Mark & Ganesh.

Manish – you should be able to exclude namespaces when TSM is installed – so I would suggest simply excluding the user packages, the order in which packages are deployed is not critical.

Ganesh can follow up with you if you have further queries since Mohana is on PTO.

Thx
Deepa
`

As per the above comment, we will add a couple of lines in the TKO 1.5 docs in the TSM installation section about excluding namespaces.

—
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvmware-tanzu-labs%2Ftanzu-validated-solutions%2Fissues%2F172%23issuecomment-1181289718&data=05%7C01%7Crerobinson%40vmware.com%7Ca6ad987effb64f964de108da63bbd61c%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637931955671943004%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=y4dR%2FjAIFdSrxwcRd%2FHz8kylBbaerPytlZjGLZbpNQs%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYSZZI4Y53QEYWZPOSXMVZTVTTVKVANCNFSM5UPOLQPA&data=05%7C01%7Crerobinson%40vmware.com%7Ca6ad987effb64f964de108da63bbd61c%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637931955671943004%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Go8ezwFCqmiRz6XPoAc9pU2JY0YjLcH60D3VNOwTGdM%3D&reserved=0>.
You are receiving this because you were assigned.Message ID: ***@***.***>

________________________________

⚠ External Email: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender.

**Comment by manishjha86** [comment]
fixed the issue via pull request https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/pull/255
