### ISSUE TITLE
Tanzu Application Platform - Include core/vCPU estimates in four node Reference Design

### ISSUE THREAD

**Issue by mbentley** [vmware-tanzu-labs/tanzu-validated-solutions#178]
**Is your feature request related to a problem? Please describe.**
With the [Tanzu Application Platform reference design](https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/blob/main/src/reference-designs/tap-architecture-planning.md), it has taken a single full deployment and spread it across multiple clusters.  With the four cluster design, there are services that are running on multiple clusters so it seems highly likely that the original 12 core/24 vCPU recommendation for a TAP full profile installation is not sufficient.

**Describe the solution you'd like**
From a resource requirement standpoint, it's not clear what is required in terms of the approximate number of cores or vCPUs to run a four cluster design.  The documentation touches upon resource requirements in terms of cores which would be approximately the equivalent of 24 vCPU for a full TAP installation but is there any guidance that can be given for a four cluster design?

**Describe alternatives you've considered**
Guessing and over-allocate resources?

**Additional context**
n/a

**Comment by sendjainabhi** [comment]
This is for each cluster requirement. so you may need 4 k8 cluster for 4 tap profile of same size.

**Comment by sendjainabhi** [comment]
Clarification have been provided in above.
