### ISSUE TITLE
[TKO RAs vSphere] Need an extension to show how to use Avi Enterprise for integrated L4-L7

### ISSUE THREAD

**Issue by jaimegag** [vmware-tanzu-labs/tanzu-validated-solutions#20]
We need an extension to show how to use Avi Enterprise for integrated L4-L7.

The doc mentions `NSX Advanced Load Balancer Essentials` but TKO also includes `NSX Advanced Load Balancer Enterprise` in the bundle. This is a key use case that is part of TKO. We have validation from the field team that some customers do get value in using AVI for L7 Ingress.
Because we are telling customers that we can support this use case via TKO, we will need to show them how they can do this and ensure Avi Enterprise is tested and interoperable with the other TKO components for this use case.

We agree with the decision to focus first on the "base" RA that would include Avi Essentials for L4 + Contour as an ingress controller. And AVI L7 should be a fast follow up.

In case it helps here's some existing docs and assets. We should document the ClusterIP mode. The NodePortLocal mode will be default soon but it will be supported on TKG 1.5 only. NodePort mode might be the choice for smaller customers (Commercial sector):
- L7 Ingress in the TKG 1.4 Docs: https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.4/vmware-tanzu-kubernetes-grid-14/GUID-networking-configure-l7.html 
- Confluence page (predecessor of the docs page above): https://confluence.eng.vmware.com/pages/viewpage.action?pageId=862154915
- Miro Board with diagrams for L7 Ingress options: https://miro.com/app/board/o9J_lUj0Bnw=/ 
- Presentation with diagrams, pros-cons of each L7 option, and examples of the experience with each case: https://onevmw-my.sharepoint.com/:p:/g/personal/jgonzalezagu_vmware_com/ESUrAoUqmMxBhsXK8pWY1R0BYNJSCUMZY4tL-b0rBIvWAw?e=bVK6JY

**Comment by manishjha86** [comment]
@jaimegag by extension do you mean a sample application deployed as type ingress? 

Also, I am unable to access the link: https://onevmw-my.sharepoint.com/:p:/g/personal/jgonzalezagu_vmware_com/ESUrAoUqmMxBhsXK8pWY1R0BYNJSCUMZY4tL-b0rBIvWAw?e=bVK6JY

Can you please re-share it.

**Comment by manishjha86** [comment]
Sure @jaimegag we will add a dedicated section for L7 ingress in RA/DG 3.0

**Comment by manishjha86** [comment]
This will be addressed in RA 3.0

**Comment by smuthukumar-vmw** [comment]
https://docs.vmware.com/en/VMware-Tanzu-for-Kubernetes-Operations/2.1/tko-reference-architecture/GUID-reference-designs-tko-on-vsphere.html address the AVI L7 integration for Enterprise Edition.
