### ISSUE TITLE
CLI-Managed Packages external-dns dynamic DNS update is not working

### ISSUE THREAD

**Issue by osmanchien** [vmware-tanzu-labs/tanzu-validated-solutions#202]
**Describe the bug**
Please provide a clear and concise description of what the bug is.
ExternalDNS dynamic DNS update to Microsoft DNS is not working with AKO L7 ingress deployed in the shared/workload cluster. 

**To Reproduce**
Please provide the steps to reproduce the behavior or a description of the content defect.

https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/blob/main/src/deployment-guides/tko-on-vsphere-with-tanzu.md#--deploy-user-managed-packages-on-tanzu-kubernetes-grid-clusters

1. Deploy a supervisor cluster with NSX ALB in vSphere Web Client.
2. Create a Namespace with proper resources.
3. Create a shared or workload cluster.
4. Deploy AKO L7 ingress for the workload cluster and configure DNS delegation for a domain that is different from the TKG packages registered. (Ingress service testing OK.)
5. Install TKG Standard Packages on the workload cluster. (Cert-manager -> Contour -> external-dns (RFC2136) -> Prometheus -> Grafana)
6. No error occurred, but the dynamic DNS update of Grafana is not working. I have to manually add the DNS record to the Microfost DNS server.
7. The Same test without AKO L7 ingress deployed, the DNS update is working as expected.

**Expected behavior**
ExternalDNS dynamic DNS update should be working, just like the same test without AKO L7 ingress deployed.

**Screenshots**
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/48082421/171313966-0523ab17-1a91-49cf-b5bf-406eba118e70.png">

**Additional context**
ExternalDNS Values file:
<img width="458" alt="image" src="https://user-images.githubusercontent.com/48082421/171313480-a4336109-1c5d-4f2e-87f3-d61a681820e9.png">

external-dns log: NOTE: ingress1.tanzu.corp.local is a testing service of AKO L7 ingress.

```
time="2022-06-01T01:44:11Z" level=info msg="Adding RR: ingress1.tanzu.corp.local 0 A 192.168.140.8"
time="2022-06-01T01:44:11Z" level=info msg="Adding RR: prometheus.corp.local 0 A 192.168.140.10"
time="2022-06-01T01:44:11Z" level=info msg="Adding RR: external-dns-ingress1.tanzu.corp.local 0 TXT \"heritage=external-dns,external-dns/owner=tanzu,external-dns/resource=ingress/default/avisvcingress\""
time="2022-06-01T01:44:11Z" level=info msg="Adding RR: external-dns-prometheus.corp.local 0 TXT \"heritage=external-dns,external-dns/owner=tanzu,external-dns/resource=HTTPProxy/tanzu-system-monitoring/prometheus-httpproxy\""
time="2022-06-01T01:44:11Z" level=info msg="Bad dns.Client.Exchange response: ;; opcode: UPDATE, status: REFUSED, id: 991\n;; flags: qr; QUERY: 1, ANSWER: 0, AUTHORITY: 4, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;corp.local.\tIN\t SOA\n\n;; AUTHORITY SECTION:\ningress1.tanzu.corp.local.\t0\tIN\tA\t192.168.140.8\nprometheus.corp.local.\t0\tIN\tA\t192.168.140.10\nexternal-dns-ingress1.tanzu.corp.local.\t0\tIN\tTXT\t\"heritage=external-dns,external-dns/owner=tanzu,external-dns/resource=ingress/default/avisvcingress\"\nexternal-dns-prometheus.corp.local.\t0\tIN\tTXT\t\"heritage=external-dns,external-dns/owner=tanzu,external-dns/resource=HTTPProxy/tanzu-system-monitoring/prometheus-httpproxy\"\n"
time="2022-06-01T01:44:11Z" level=error msg="RFC2136 update failed: bad return code: REFUSED"
time="2022-06-01T01:44:11Z" level=error msg="RFC2136 had errors in one or more of its batches: [bad return code: REFUSED]"
```
external-dns log without AKO: NOTE: Same Microsoft DNS configuration as above.
```
time="2022-06-01T03:25:18Z" level=info msg="Adding RR: prometheus.corp.local 0 A 192.168.140.9"
time="2022-06-01T03:25:18Z" level=info msg="Adding RR: external-dns-prometheus.corp.local 0 TXT \"heritage=external-dns,external-dns/owner=tanzu,external-dns/resource=HTTPProxy/tanzu-system-monitoring/prometheus-httpproxy\""
...
W0601 03:27:12.260161       1 transport.go:288] Unable to cancel request for *instrumented_http.Transport
time="2022-06-01T03:27:19Z" level=info msg="Adding RR: grafana.corp.local 0 A 192.168.140.9"
time="2022-06-01T03:27:19Z" level=info msg="Adding RR: external-dns-grafana.corp.local 0 TXT \"heritage=external-dns,external-dns/owner=tanzu,external-dns/resource=HTTPProxy/tanzu-system-dashboard/grafana-httpproxy\""
```

**Comment by nithink-vmw** [comment]
@osmanchien Current RA and DG doesn't cover external DNS configuration.If you suspect its a bug, please file Jira-Bug against Avi.
