### ISSUE TITLE
Deployment guide doesn't match VMware docs

### ISSUE THREAD

**Issue by etrinhh** [vmware-tanzu-labs/tanzu-validated-solutions#217]
The VMware docs for TKG 1.4 says it's compatible with AVI 20.1.6 and not 20.1.7 (what's in the deployment guide).

**Comment by manishjha86** [comment]
I checked the TKO 1.4 docs (vSphere VDS, vSphere NSX-T, VMC on AWS, and vSphere with Tanzu) and in none of the docs we have called out to use NSX ALB 20.1.7.

@etrinhh can you please point to the doc/section in the doc where 20.1.7 is mentioned?

**Comment by etrinhh** [comment]
https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/blob/main/src/deployment-guides/tko-on-vsphere-nsxt.md#supported-component-matrix

https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/blob/main/src/deployment-guides/tko-on-vsphere-nsxt.md#supported-component-matrix

https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/blob/main/src/deployment-guides/tko-on-vsphere-with-tanzu.md#--general-requirements

https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/blob/main/src/deployment-guides/tko-on-vsphere-with-tanzu.md#deploy-nsx-advance-load-balancer-controller-node

**Comment by nithink-vmw** [comment]
@etrinhh  - TKGm1.5.1 support Avi 20.1.7 - Please check the compatibility Matrix. https://interopmatrix.vmware.com/Interoperability?col=789,6104&row=551,

**Comment by manishjha86** [comment]
@etrinhh the links that you shared are for TKGm 1.5 which very well supports NSX ALB 20.1.7. Please see the interop matrix link provided by Nithin.
