### ISSUE TITLE
TKO-AWS Deployment Guide Update

### ISSUE THREAD

**Issue by samiksha-j** [vmware-tanzu-labs/tanzu-validated-solutions#242]
Under Setup infrastructure , Point 6 , while creating nat gateway , parameter is “—subnet-id” and not as mentioned “subnet”.

![Screenshot 2022-08-02 at 9 45 49 AM](https://user-images.githubusercontent.com/104903906/182290737-a2e661b8-c2c9-445b-8d79-14e36e446daa.png)

**Comment by sendjainabhi** [comment]
This issue has been fixed. Plz close this issue.
