### ISSUE TITLE
TKO using NSX-T should use NSX-T cloud within AVI

### ISSUE THREAD

**Issue by calebwashburn** [vmware-tanzu-labs/tanzu-validated-solutions#245]
**Is your feature request related to a problem? Please describe.**
Currently TKO with TKG on NSX-T deployment guide references using vCenter cloud instead of NSX-T cloud.  Deployments with NSX-T vs VDS networking should use NSX-T cloud

**Describe the solution you'd like**
Update deployment guide to use NSX-T cloud

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by manishjha86** [comment]
This is planned for TKO 1.6 doc

**Comment by manishjha86** [comment]
TKO 1.6 RA/Deployment guide uses NSX-T cloud in NSX ALB. Please see below links for RA/DG

https://docs.vmware.com/en/VMware-Tanzu-for-Kubernetes-Operations/1.6/tko-reference-architecture/GUID-reference-designs-tko-on-vsphere-nsx.html

https://docs.vmware.com/en/VMware-Tanzu-for-Kubernetes-Operations/1.6/tko-reference-architecture/GUID-deployment-guides-tko-on-vsphere-nsxt.html
