### ISSUE TITLE
On TKGs workload clusters provisioned via YAML, TAP installation guide fails adding secret due to missing Carvel secretgen-controller.

### ISSUE THREAD

**Issue by itgrl-bex** [vmware-tanzu-labs/tanzu-validated-solutions#248]
**Describe the bug**
Following the TAP installation guide when you have deployed the workload clusters on vSphere with Tanzu via yaml files will not work.  There is no mention of prerequisite requirements of the kapp-controller or the secretgen-controller.  TKGs deployment guides do have the kappa-controller but no mention of the secretgen-controller.

**To Reproduce**
Please provide the steps to reproduce the behavior or a description of the content defect.
1. On a newly provisioned TKGs workload cluster via YAML, use the tanzu cli, and attempt to add a secret such as a reference in TAP deployment guide.
`# tanzu registry secret creation
tanzu secret registry add tap-registry \
  --username "${INSTALL_REGISTRY_USERNAME}" --password "${INSTALL_REGISTRY_PASSWORD}" \
  --server "${INSTALL_REGISTRY_HOSTNAME}" \
  --export-to-all-namespaces --yes --namespace "${TAP_NAMESPACE}"`
4. See error `Error: secret plugin can not be used as 'secretgen.carvel.dev/v1alpha1' API is not available in the cluster
Error: exit status 1`

**Expected behavior**
Command should result in the following output.
`| Adding registry secret 'tap-registry'...
 Added registry secret 'tap-registry' into namespace 'tap-install'
 Exported registry secret 'tap-registry' to all namespaces`

**Additional context**
PR Submitted to resolve this.
https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/pull/247

**Comment by sendjainabhi** [comment]
seems like you have missed to install tanzu essentials which install secretgen.carvel.dev/v1alpha1 controller

**Comment by smuthukumar-vmw** [comment]
@itgrl-bex Please help reopen the issue, if the suggestion from @sendjainabhi has not addressed the issue. Thanks.

**Comment by sendjainabhi** [comment]
Tap install guide has been discontinued after v1.2. Plz follow tap instructions of multi cluster.
