### ISSUE TITLE
Incorrect schema for AKODeploymentConfig in vmware-tanzu-deployment-on-vsphere.md

### ISSUE THREAD

**Issue by craigtracey** [vmware-tanzu-labs/tanzu-validated-solutions#26]
Therear currently YAML formatting issues with the AKODeploymentConfig snippets in vmware-tanzu-deployment-on-vsphere.md. These should be fixed for both style as well as schema accuracy.

**Comment by manishjha86** [comment]
This issue should be assigned to Meera. The portion where yaml content is provided needs to be updated as code format (the way other vmware docs provide references to yaml/json)

**Comment by ranjith-bp87** [comment]
In the main doc, akoDeploymentConfig has been provided in YAML code format, however, in the published document it's not in YAML format.
@srinivasme21 can you please take a look at this. Thanks.
