### ISSUE TITLE
[vSphere with vDS RA] Feedback on Diagram

### ISSUE THREAD

**Issue by jaimegag** [vmware-tanzu-labs/tanzu-validated-solutions#27]
This is feedback for the content published here: https://docs.vmware.com/en/VMware-Tanzu/services/tanzu-reference-architecture/GUID-reference-designs-tko-on-vsphere.html

The diagram under `The following diagram shows the architecture of Tanzu for Kubernetes Operations:` should be corrected on a couple of items:
- There is no component called `NSX-ALB Ingress Operator` The component name is AKO (AVI Kubernetes Operator)
- That AKO component also runs in the Management Cluster on TKG 1.4
- The Management Cluster also as an AKO Operator (AKOO) component (core add-on since TKG 1.4)

**Comment by ranjith-bp87** [comment]
This will be addressed in RA 2.0, RA diagram will look like attached. 
@srinivasme21 can we try to get the source of the attached diagram? We need to add AKO part and make use of the same.
![TKO-Ref Arch](https://user-images.githubusercontent.com/82767975/157173669-8f784ad7-f0ec-4d93-b13c-ec643847d6fa.jpg)

Once we have the source we can update the RA diagrams used in RA version 1.0 too.

**Comment by manishjha86** [comment]
Will get the source image and modify it to include AKO operator in the diagram

**Comment by manishjha86** [comment]
This has been addressed in TKO 1.5 docs as part of the pull request: https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/pull/211

**Comment by srinivasme21** [comment]
@manishjha86 , Please verify and close - 
 https://docs.vmware.com/en/VMware-Tanzu-for-Kubernetes-Operations/1.5/tko-reference-architecture/GUID-reference-designs-tko-on-vsphere.html

**Comment by manishjha86** [comment]
Hi Meera,

The TKO ref Arch image still reads NSX ALB Essentials. We already discussed last week that essentials need to be changed to the enterprise.

**Doc Link:** https://docs.vmware.com/en/VMware-Tanzu-for-Kubernetes-Operations/1.5/tko-reference-architecture/GUID-reference-designs-tko-on-vsphere.html

**Image Link:** https://docs.vmware.com/en/VMware-Tanzu-for-Kubernetes-Operations/1.5/tko-reference-architecture/Images/reference-designs-img-tko-on-vsphere-TKO-Ref-Arch.jpg
