### ISSUE TITLE
Add Pinniped Content into RA - VMC/AWS , vSphere with vds /nsx-t versions

### ISSUE THREAD

**Issue by sendjainabhi** [vmware-tanzu-labs/tanzu-validated-solutions#28]
Pinniped Content is not there into Reference design of  - VMC/AWS , vSphere with vds /nsx-t versions. Please add Pinniped section into RA design doc

**Comment by manishjha86** [comment]
Pinniped contents are currently available in G-docs. Kumar is working on converting the files in md format and once it is done, this will go as a deliverable for RA/DG 2.0

Pinniped Deployment: https://docs.google.com/document/d/1rk2WWPiB5dNd3ZzMj2tl_9ld3kEabnu6Lki5WPnAyBE/edit

Piniped RA: https://docs.google.com/document/d/1BywBxQACMzsc4eAp7qYS3xfC-QibA-SmU2K5ZMJ6On8/edit
