### ISSUE TITLE
Harbor image pull command is failing

### ISSUE THREAD

**Issue by pramitagautam** [vmware-tanzu-labs/tanzu-validated-solutions#293]
**Describe the bug**
Image url command written on RA is failing

**To Reproduce**
Use `kubectl -n tanzu-package-repo-global get packages harbor.tanzu.vmware.com/2.5.3+vmware.1-tkg.1` command written in RA.

**Expected behavior**
Image name variable should be available

**Screenshots**
`ubuntu@ip-172-16-3-166:~$ image_url=$(kubectl -n tanzu-package-repo-global get packages harbor.tanzu.vmware.com/2.5.3+vmware.1-tkg.1 -o jsonpath='{.spec.template.spec.fetch[0].imgpkgBundle.image}')
error: there is no need to specify a resource type as a separate argument when passing arguments in resource/name form (e.g. 'kubectl get resource/<resource_name>' instead of 'kubectl get resource resource/<resource_name>'`

**Additional context**
It can be fixed by using below:-
`ubuntu@ip-172-16-3-166:~$ image_url=$(kubectl -n tanzu-package-repo-global get packages harbor.tanzu.vmware.com.2.5.3+vmware.1-tkg.1 -o jsonpath='{.spec.template.spec.fetch[0].imgpkgBundle.image}')
ubuntu@ip-172-16-3-166:~$`

**Comment by pramitagautam** [comment]
I have tested this on TKG 1.6 on AWS Cloud.

**Comment by sendjainabhi** [comment]
you should test this for tkg 1.5 . tk0-dg for 1.6 is still in progress

**Comment by smuthukumar-vmw** [comment]
@sendjainabhi we are validating AWS RA on 1.6 referring from https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.6/vmware-tanzu-kubernetes-grid-16/GUID-packages-harbor-registry.html which had the versioning from 1.5
I find that the changes have been incorporated in the 1.6 RA recently. Thanks for it. 

@pramitagautam @nithink-vmw please check if the updated changes are resolving the issue. Thanks.

**Comment by pramitagautam** [comment]
@smuthukumar-vmw Yes its resolving the issue. Closing the bug.
