### ISSUE TITLE
Overlay file ( ~/.config/tanzu/tkg/providers/infrastructure-aws/ytt/aws-overlay.yaml ) update for AWS is failing 

### ISSUE THREAD

**Issue by pramitagautam** [vmware-tanzu-labs/tanzu-validated-solutions#305]
**Describe the bug**

I am following this guide for creating airgap env :-https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.6/vmware-tanzu-kubernetes-grid-16/GUID-mgmt-clusters-airgapped-environments.html

As suggested by step 5 under, step-1: Prepare your env, I updated the overlay file.
but when creating the mgmt cluster I am getting the below error:-
` 
Using default value for CONTROL_PLANE_MACHINE_COUNT = 3. Reason: CONTROL_PLANE_MACHINE_COUNT variable is not set
Fetching File="cluster-template-definition-prod.yaml" Provider="aws" Type="InfrastructureProvider" Version="v1.2.0"
Deleting kind cluster: tkg-kind-cdmujsch0pqfj5402pgg
Error: unable to set up management cluster: unable to build management cluster configuration: unable to get template: Overlaying (in following order: overlay.yaml, aws-overlay.yaml, 01_plans/prod.yaml, 02_addons/cni/add_cni.yaml, 03_customizations/annotate_os_info.yaml, 03_customizations/registry_ca_cert.yaml, 03_customizations/registry_skip_tls_verify.yaml): Document on line aws-overlay.yaml:201: Map item (key 'spec') on line aws-overlay.yaml:202: Map item (key 'kubeadmConfigSpec') on line aws-overlay.yaml:203: Map item (key 'preKubeadmCommands') on line aws-overlay.yaml:204: Expected number of matched nodes to be 1, but was 0
Error: exit status 1
✖  exit status 1
`

This issue got resolved when I added `#@overlay/match missing_ok=True` just below kubeadmConfigSpec, like this:-

`#@ load("@ytt:overlay", "overlay")`
`#@overlay/match by=overlay.subset({"kind":"KubeadmControlPlane"})`
`---`
`spec:`
  `kubeadmConfigSpec:`
   ` #@overlay/match missing_ok=True`
    `preKubeadmCommands:`
    `#! Add nameserver to all k8s nodes`
    `#@overlay/append`

**Comment by smuthukumar-vmw** [comment]
This issue has not been reproduced recently. Please open a new bug if encountered.
