### ISSUE TITLE
Pinniped info review

### ISSUE THREAD

**Issue by jaimegag** [vmware-tanzu-labs/tanzu-validated-solutions#31]
I noticed we mention LDAP in the title of the Pinniped section, but there is no other mention in the doc. Everything is OIDC related only.

Also here's a more detailed diagram that shows the differences that exist today on how the LDAP and OIDC integrations happen. Also more detail on the client component to reflect the Tanzu CLI involvement
https://onevmw.sharepoint.com/:i:/s/TKG-TSL/EZph_9wBnMRNnRXzh0E7e6EBAjR68AIjUMQsXEGg3iws9w?e=1f6h55
This is compliant with both TKGm 1.3.1 and 1.4.0 versions

**Comment by srivar** [comment]
This is being delivered in TKO RA v1.5
