### ISSUE TITLE
Deploy Tanzu for Kubernetes Operations on Azure - Azure ARM template validation error

### ISSUE THREAD

**Issue by pete-reis** [vmware-tanzu-labs/tanzu-validated-solutions#310]
[https://docs.vmware.com/en/VMware-Tanzu-for-Kubernetes-Operations/1.6/tko-reference-[…]ID-deployment-guides-resources-tko-on-azure-azure-deploy.json](https://docs.vmware.com/en/VMware-Tanzu-for-Kubernetes-Operations/1.6/tko-reference-architecture/GUID-deployment-guides-resources-tko-on-azure-azure-deploy.json)

Both 1.5 and 1.6 kick back errors on public IP Prefix resource.

**Comment by gradinDotCom** [comment]
Procedures for TKO on public cloud is most recently maintained as a Terraform/script sequence for a more comprehensive solution. This now lives within the SIVT project which provides automation for on-prem deployments as well: https://github.com/vmware-tanzu/service-installer-for-vmware-tanzu
