### ISSUE TITLE
VM Harbor reference should point to the OVA

### ISSUE THREAD

**Issue by laidbackware** [vmware-tanzu-labs/tanzu-validated-solutions#373]
**Describe the bug**
From TKG 2.1 Harbor is available as a OVA for customers that need to host TKG system images. The Harbor section should be updating to replace statements about docker-compose

**Comment by smuthukumar-vmw** [comment]
This will be addressed in the upcoming RA update

**Comment by smuthukumar-vmw** [comment]
This has been completed in 2.3 RA.
