### ISSUE TITLE
Azure RA need worker node NSG to be in the format ClusterName-node-nsg for both mgmt and workload cluster

### ISSUE THREAD

**Issue by srivar** [vmware-tanzu-labs/tanzu-validated-solutions#42]
n order for mgmt and workload cluster to get LB ip for there Application , we need the worker node nsg to be in the form of "ClusterName-node-nsg", otherwise svc external ip for app will be in <pending > state.

This change is required to be made for RA azure . 

https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.4/vmware-tanzu-kubernetes-grid-14/GUID-mgmt-clusters-azure.html#network-security-groups-on-azure-2

**Comment by srivar** [comment]
https://jira.eng.vmware.com/projects/MAPBUA/issues/MAPBUA-427

**Comment by brharr** [comment]
Fixed in the latest piece of code and Pull request that was recently submitted.
