### ISSUE TITLE
Update RA/DG/Automation to support TKGm 1.5

### ISSUE THREAD

**Issue by srivar** [vmware-tanzu-labs/tanzu-validated-solutions#45]
Desired ETA is February end.

- [x] VMC
  - [x] #98
  - [x] #101
  - [x] VMC Refresh automation to match deployment guide
- [x] vSphere
  - [x] vSphere Refresh reference architecture for TKGm 1.5
  - [x] vSphere Refresh deployment guide for TKGm 1.5
  - [x] vSphere Refresh automation to match deployment guide
- [x] VCF
  - [x] VCF Refresh reference architecture for TKGm 1.5
  - [x] VCF Refresh deployment guide for TKGm 1.5
  - [x] VCF Refresh automation to match deployment guide
- [ ] AWS
  - [ ] AWS Refresh reference architecture for TKGm 1.5
  - [ ] AWS Refresh deployment guide for TKGm 1.5
  - [ ] AWS Refresh automation to match deployment guide
- [ ] Azure
  - [ ] Azure Refresh reference architecture for TKGm 1.5
  - [ ] Azure Refresh deployment guide for TKGm 1.5
  - [ ] Azure Refresh automation to match deployment guide

**Comment by joefitzgerald** [comment]
It's probably worth breaking this issue up into five separate issues, and tracking them all against the [TKGm v1.5](https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/milestone/1) milestone.

**Comment by manishjha86** [comment]
Updated the status for VMC/vSphere and VCF (NSX-T)
