### ISSUE TITLE
Update Azure 1.4 Deployment guide to not use 1.3 extensions

### ISSUE THREAD

**Issue by aizurov-vmw** [vmware-tanzu-labs/tanzu-validated-solutions#47]
https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/blob/main/src/deployment-guides/tko-on-azure.md

For TKG 1.4 this should be using the tanzu package install and not the extensions from 1.3.

>Unpack the manifest using the following command.
> tar -xzf tkg-extensions-manifests-v1.3.1-vmware.1.tar.gz

**Comment by srivar** [comment]
We'll fix this in 1.5 DG/Automation. Will consider backporting to 1.4 if there's demand from external customers or SE teams.

**Comment by z4ce** [comment]
This was fixed and you can see that everything is up to date for 1.4 ( https://docs.vmware.com/en/VMware-Tanzu/services/tanzu-reference-architecture/GUID-deployment-guides-tko-on-azure.html ) .
