### ISSUE TITLE
Clarify quota requirements for the Azure Deployment Guide

### ISSUE THREAD

**Issue by aizurov-vmw** [vmware-tanzu-labs/tanzu-validated-solutions#48]
https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/blob/main/src/deployment-guides/tko-on-azure.md

Please provide and example set of quota specific requirements, similar to the published Azure getting started guide here:

https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.4/vmware-tanzu-kubernetes-grid-14/GUID-mgmt-clusters-azure.html#general-requirements-1

Current text of "When deploying TKG to Azure you will need to make sure your quotas are sufficient to support both the Management Cluster and Workload Cluster deployments otherwise the deployments will fail. The following quotas will likely need to be increased from their default values." is vague.

**Comment by srivar** [comment]
https://jira.eng.vmware.com/browse/MAPBUA-439

**Comment by brharr** [comment]
A section was added in the latest deployment guide to include minimum Quota requirements.
