### ISSUE TITLE
[TKO vSphere with Tanzu RA] Remove References to vSphere Pods

### ISSUE THREAD

**Issue by doddatpivotal** [vmware-tanzu-labs/tanzu-validated-solutions#50]
Initial sentence (vSphere with Tanzu transforms vSphere into a platform for running Kubernetes workloads natively on the hypervisor layer.) is misleading since vSphere pods is not supported with VDS networking. 

Again in first bullet point of "Supervisor Cluster" definition

**Comment by ranjith-bp87** [comment]
@doddatpivotal point taken and is not included in RA 2.0. We will review and anything pointing to vSphere pods will be included in RA 2.0
@srinivasme21 can we please get the below section removed from https://docs.vmware.com/en/VMware-Tanzu/services/tanzu-reference-architecture/GUID-reference-designs-tko-on-vsphere-with-tanzu.html

`vSphere with Tanzu transforms vSphere into a platform for running Kubernetes workloads natively on the hypervisor layer. When vSphere with Tanzu is enabled on a vSphere cluster, you can run Kubernetes workloads directly on ESXi hosts and create upstream Kubernetes clusters within dedicated resource pools.`

**Comment by manishjha86** [comment]
Will address this in RA 2.0

**Comment by manishjha86** [comment]
Addressed this in my latest commit to the vwt ra pull request
