### ISSUE TITLE
[TKO vSphere with Tanzu RA] Be clear about Avi Enterprise for Ingress

### ISSUE THREAD

**Issue by doddatpivotal** [vmware-tanzu-labs/tanzu-validated-solutions#51]
Avi Enterprise key value proposition is ingress services.

TKO includes Avi Enterprise and for this RA specifically, it should be written based upon Avi Enterprise use for Layer 7 load balancing.

I recognize that the integrations are a big confusing right now, but this RA should show the current state of how to work within the current integrations.

1. I don't think the following sentence is true "The Supervisor Cluster leverages NSX Advanced Load Balancer (NSX ALB) to provide L4 load balancing for the Tanzu Kubernetes Clusters and L7 ingress to the applications deployed in the Tanzu Kubernetes Clusters"
2. Need better explanation of deploying AKO on workload clusters.  And recommendation to use ClusterIP for Layer 7.  Then that you need to create service engine groups for each vSphere namespace.  And that each TKC within the vSphere namespace should have non-overlapping cluster IP CIDR.  The network overview picture should show AVI SEs in the workload /24 for layer 7
3. Should be overt and opinionated about using AVI for ingress.  The intro to https://docs.vmware.com/en/VMware-Tanzu/services/tanzu-reference-architecture/GUID-reference-designs-tko-on-vsphere-with-tanzu.html#kubernetes-ingress-routing-16 is weak in this opinion.  Given this is TKO and TKO includes Avi Enterprise, it should not be weak.

**Comment by manishjha86** [comment]
We will remove the reference to L7 ingress in the VWT doc.  Currently, this is not supported by the product team. Once the support is available, We will add it to the RA/Deploy Guide
