### ISSUE TITLE
[TKO vSphere with Tanzu RA] Firewall Recommendations

### ISSUE THREAD

**Issue by doddatpivotal** [vmware-tanzu-labs/tanzu-validated-solutions#52]
1. Should be more specific in destination for the TMC,TO and TSM row.
2. Also need to reference required access to projects.registry.vmware.com for TKCs (this is for installation of tanzu standard repo and harbor OSS helm)
3. Should mention that vCenter requires access OVA subscripion URL for content library

For 2 and 3 above, may also have a note and appropriate references for how this would work in air gap.

**Comment by nithink-vmw** [comment]
It has been fixed in the latest doc, please review  https://confluence.eng.vmware.com/display/CNA/Tanzu+Reference+Architectures
