### ISSUE TITLE
[TKO vSphere with Tanzu RA] TMC Secion

### ISSUE THREAD

**Issue by doddatpivotal** [vmware-tanzu-labs/tanzu-validated-solutions#53]
1. Says you should "attach" supervisor cluster and TKCs. Should actually register and mange.
2. Why reference Tanzu Mission Control Standard when you are talking about TKO which includes TMC Advanced.

**Comment by ranjith-bp87** [comment]
We have this addressed in RA 2.0
Even in RA 1.0 we meant "register", probably choose the wrong word while documenting it.

**Comment by srivar** [comment]
per ranjith comment (previous), this is fixed in RA v1.5.
