### ISSUE TITLE
RA/DG/Automation for TKO on VMware Cloud Director

### ISSUE THREAD

**Issue by srivar** [vmware-tanzu-labs/tanzu-validated-solutions#56]
Needs to include details on TMC/TO/TSM consumption through CPN (Cloud Partner Navigator).

Phase 1 should be focused on Tanzu Standard (TKGm) + VCD + CPN.
Phase 2 should expand to include remaining parts of TKO (TMC, TO, NSX ALB).

**Comment by ranjith-bp87** [comment]
Phase 1 is complete which includes NSX ALB
CPN integration is in progress and is considered to be part of Phase2 which includes TMC and TO.
