### ISSUE TITLE
[TKO vSphere with Tanzu RA] F5 as LB / NSX-T / Calico CNI

### ISSUE THREAD

**Issue by huxoll** [vmware-tanzu-labs/tanzu-validated-solutions#61]
We have a customer request for TKG with F5 as load balancer, NSX-T, Calico as CNI.

It seems like lots of customers will already have an enterprise load balancer, so integration with existing LB would be a good section to add.

**Comment by msegvich** [comment]
This relates to #89.

**Comment by manishjha86** [comment]
TKGS with NSX-T and NSX-ALB will be supported vSphere 8.0 onwards. Once the product supports it, we will publish a RA

Instructions for using Calico CNI are already part of the RA.

Regarding F5 as LB, how critical this ask is?

**Comment by srivar** [comment]
RAs won't get into documenting support for 3rd-party LBs, like F5.

TKGs + NSX-T RA is coming in via https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/pull/203.
