### ISSUE TITLE
Default Cloud Type selection UI for AVI has changed

### ISSUE THREAD

**Issue by kcalmond** [vmware-tanzu-labs/tanzu-validated-solutions#62]
Re [Deploy Tanzu for Kubernetes Operations using vSphere with Tanzu](https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/blob/main/src/deployment-guides/tko-on-vsphere-with-tanzu.md) deployment guide, need to update the Controller Node configuration section with current screen shot for changing Default-Cloud type to Vmware vCenter/vSphere ESX. See attached image.
![Avi_Vantage_Controller-DefaultCloudType](https://user-images.githubusercontent.com/12177199/152453014-578948e4-bf72-4063-aac5-08d6efc2d3ea.png)

**Comment by manishjha86** [comment]
This screenshot is from NSX ALB version 21.1.x. We are not supporting this version. 20.1.6 and 20.1.7 are the tested versions. That is why our documents are referencing screenshots from 20.1.x versions of ALB.

This issue can be closed as no action is needed.
