### ISSUE TITLE
Feedback from the field: Bootstrapping instructions need a look

### ISSUE THREAD

**Issue by bcdurden** [vmware-tanzu-labs/tanzu-validated-solutions#66]
I was viewing the instructions here:
https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/blob/main/src/deployment-guides/tko-aws.md

I think a better delivery artifact here would be a base terraform that does all of these things. A best practice and validated solution in my opinion should be showing how to build the system using configuration-as-code concepts so they may be easily adapted in new and existing engagements. While manual aws-cli commands are useful in illustrating the dependencies, I think walking through a Terraform module would be more useful and applicable to how these systems are used in the real world. 

There's been multiple engagements where this has already been done so I suspect it could be copied and adapted with minimal changes. I have non-scrubbed Terraform code over in vmware-tanzu-labs/tkg-ag-solution. It expects a pre-existing transit-gateway to bind to, but should be adaptable enough if you need a starting point.

**Comment by sendjainabhi** [comment]
we have tko-aws automation using terraform - check this pull request #38
