### ISSUE TITLE
Add references to shared services cluster to TKO on AWS RA and deployment

### ISSUE THREAD

**Issue by srinivasme21** [vmware-tanzu-labs/tanzu-validated-solutions#77]
tko-on-aws reference architecture: Cluster Creation and Management: Update the last sentence in the section. Remove reference to Tanzu Editions and provide examples for which components should be installed on a shared services cluster. 

tko-on-aws reference architecture: Add instruction for creating a shared services cluster.

**Comment by sendjainabhi** [comment]
issue has addressed into https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/pull/96

**Comment by srinivasme21** [comment]
Closing this issue since it is captured in #96
