### ISSUE TITLE
Add reference to shared services cluster in TKO on vSphere with Tanzu RA and deployment docs

### ISSUE THREAD

**Issue by srinivasme21** [vmware-tanzu-labs/tanzu-validated-solutions#79]
tko-on-vsphere-with-tanzu reference architecture: Do we need to add a Tanzu Kubernetes shared services workload cluster? How are services shared?
In the deployment guide add instructions for creating a shared services cluster. Is it the same as creating a workload cluster?

**Comment by manishjha86** [comment]
There is no concept of a shared services cluster in vSphere with Tanzu. Shared Services clusters are nothing but a workload cluster with a specific role label applied. TKO for vSphere with Tanzu deployment guide does not refer to shared services cluster anywhere.

There is no action needed on this issue.

**Comment by srivar** [comment]
Per comments from Manish, vSphere with Tanzu RA doesn't require this. Its already featured in TKG-multi cloud RAs. So closing this issue.
