### ISSUE TITLE
build Customer Outcome "Deploy TKO in Internet-Restricted Environments"

### ISSUE THREAD

**Issue by srivar** [vmware-tanzu-labs/tanzu-validated-solutions#8]
Document all the constraints/changes in deployment of the RA when deploying to an internet-restricted environment:

1. vSphere envs with Proxy-based internet access
2. vSphere envs with no internet access
3. Public Clouds with Proxy-based access that require you to list allowed URLs that you'll connect out to
4. Usage of Prometheus/Grafana instead of TO
5. Document config/setup of MITM proxy as a aid to the user
6. Test & document Pinniped behavior in clusters w/o internet connectivity

TBD - any solutions to replace TMC & TSM functionality?

**Comment by msegvich** [comment]
This isn't TKO, so changed title and moved to a separate milestone.

**Comment by srivar** [comment]
This was done as part of RA v1.4. Manish built a standalone customer outcome doc.
