### ISSUE TITLE
Installation experience section missing from "TKO on vSphere with Tanzu" (with VDS) RA

### ISSUE THREAD

**Issue by yaitspuneet** [vmware-tanzu-labs/tanzu-validated-solutions#80]
The "Installation experience" section in the Public documentation of  "TKO on vsphere with VDS" (tko-on-vsphere-with-tanzu.md) is missing. 
The VMware Internal google docs does contain the "Installation experience section"

**Comment by manishjha86** [comment]
Will add this section in v2.0 of the RA

**Comment by manishjha86** [comment]
Added installation experience in RA 2.0. This issue can be closed now.

**Comment by ranjith-bp87** [comment]
@srinivasme21 can you please take look at it and see if we can get this included in RA 1.0 too?

**Comment by manishjha86** [comment]
Closing this issue as we have fixed this already in v2.0 of the doc.
