### ISSUE TITLE
Link to docs.wavefront.com

### ISSUE THREAD

**Issue by srinivasme21** [vmware-tanzu-labs/tanzu-validated-solutions#88]
Feedback from Renate Kempf. 

Might it make sense to have a link from https://docs.vmware.com/en/VMware-Tanzu/services/tanzu-reference-architecture/GUID-deployment-guides-tko-saas-services.html#to to [docs.wavefront.com](http://docs.wavefront.com/).

Getting the handshake in place is only the first step. There are a lot of customizations that users can do.

**Comment by rkempf42** [comment]
I see Tanzu Observability mentioned in several other places. In each case, I recommend that the TObs docs team is asked for a review. We can ask our SMEs to give feedback. And I recommend adding links to docs.wavefront.com. 
* https://docs.vmware.com/en/VMware-Tanzu/services/tanzu-reference-architecture/GUID-reference-designs-tko-on-vmc-aws.html#observability-28 
* https://docs.vmware.com/en/VMware-Tanzu/services/tanzu-reference-architecture/GUID-reference-designs-tko-on-vsphere-nsx.html#observability-23 
* https://docs.vmware.com/en/VMware-Tanzu/services/tanzu-reference-architecture/GUID-reference-designs-tko-on-aws.html#observability-12 
* https://docs.vmware.com/en/VMware-Tanzu/services/tanzu-reference-architecture/GUID-reference-designs-tko-on-azure.html#observability-25
* https://docs.vmware.com/en/VMware-Tanzu/services/tanzu-reference-architecture/GUID-deployment-guides-tko-saas-services.html#set-up-tanzu-observability-to-monitor-a-tanzu-kubernetes-clusters-5

Will be important to ask some questions about 
* Required permissions. How to log into TObs (it's not seamless). BTW, the **Accounts, Groups, and Roles** permission was renamed to **Accounts**. 
* Which integrations users need. 
* Which dashboards in those integrations users need. 
(Right now, I see screenshots of dashboards, but it's not clear which integration each dashboards belongs to.

**Comment by manishjha86** [comment]
We will add the links to docs.wavefront in all RA/DG 2.0 docs.

Regarding customization/custom dashboards, Aman is working on a dedicated file for this and will be added to our main repo and then all RA/DG will reference to that doc.

**Comment by manishjha86** [comment]
This has been addressed in TKO 1.5 docs as part of the pull request: https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/pull/211
