### ISSUE TITLE
"What's New" section

### ISSUE THREAD

**Issue by msegvich** [vmware-tanzu-labs/tanzu-validated-solutions#95]
**Is your feature request related to a problem? Please describe.**
With new versions of RAs it's not clear what in general has changed? Is it a minor change or major?  Having highlights ensure I don't have to read the whole document to realize only a few things or even just the BOM has changed.

**Describe the solution you'd like**
A "What's new" or "Release Notes" section would help with this. I like what [TMC did for this](https://docs.vmware.com/en/VMware-Tanzu-Mission-Control/services/rn/VMware-Tanzu-Mission-Control-Release-Notes.html).

**Comment by srivar** [comment]
Dup of https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/issues/100.

@msegvich add your addl. asks to this other issue.
