### ISSUE TITLE
VMC RA should call out its focus on user-managed TKGm

### ISSUE THREAD

**Issue by srivar** [vmware-tanzu-labs/tanzu-validated-solutions#97]
**Describe the bug**
Existing TKO RA for VMC/AWS is focused on user-installed TKGm. It does not cover the VMC-native experience which is centered on TKGs. Marketing and VMC PM teams have expressed concerns this will confuse VMC customers.

**Expected behavior**
Feedback from Marketing team - it will be beneficial to start with an high level chapter that explain the target environment (customer-installed and managed TKGm) and components chosen and which components don't work. and then start with the install steps.

**Comment by ranjith-bp87** [comment]
@srivar in the RA and deployment guide we can clearly mention this is a user-managed solution.
Except for TMC, we do not find any compatible issues in VMC environment. Assigning it to Manish to get the documentation sorted.

**Comment by manishjha86** [comment]
I will add this in RA 2.0

**Comment by manishjha86** [comment]
I have added this in my local repo. Once I receive the ix reviewed md file, I will merge it in my local and commit the changes.
